# Generated by Django 5.1.6 on 2025-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('coord', models.CharField(max_length=100)),
            ],
        ),
    ]
