# Generated by Django 5.1.6 on 2025-03-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='coord',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='last_seen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
