# Generated by Django 5.1.6 on 2025-03-25 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSocket', '0002_sensordata_device_id_alter_sensordata_coord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='coord',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='coord_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='next_nearest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='next_nearest_direction',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='device_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='last_seen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
